// Package karakeep provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package karakeep

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BookmarkAssetsAssetType.
const (
	BookmarkAssetsAssetTypeAssetScreenshot   BookmarkAssetsAssetType = "assetScreenshot"
	BookmarkAssetsAssetTypeAvatar            BookmarkAssetsAssetType = "avatar"
	BookmarkAssetsAssetTypeBannerImage       BookmarkAssetsAssetType = "bannerImage"
	BookmarkAssetsAssetTypeBookmarkAsset     BookmarkAssetsAssetType = "bookmarkAsset"
	BookmarkAssetsAssetTypeFullPageArchive   BookmarkAssetsAssetType = "fullPageArchive"
	BookmarkAssetsAssetTypeLinkHtmlContent   BookmarkAssetsAssetType = "linkHtmlContent"
	BookmarkAssetsAssetTypePdf               BookmarkAssetsAssetType = "pdf"
	BookmarkAssetsAssetTypePrecrawledArchive BookmarkAssetsAssetType = "precrawledArchive"
	BookmarkAssetsAssetTypeScreenshot        BookmarkAssetsAssetType = "screenshot"
	BookmarkAssetsAssetTypeUnknown           BookmarkAssetsAssetType = "unknown"
	BookmarkAssetsAssetTypeUserUploaded      BookmarkAssetsAssetType = "userUploaded"
	BookmarkAssetsAssetTypeVideo             BookmarkAssetsAssetType = "video"
)

// Defines values for BookmarkContent0CrawlStatus.
const (
	BookmarkContent0CrawlStatusFailure     BookmarkContent0CrawlStatus = "failure"
	BookmarkContent0CrawlStatusLessThannil BookmarkContent0CrawlStatus = "<nil>"
	BookmarkContent0CrawlStatusPending     BookmarkContent0CrawlStatus = "pending"
	BookmarkContent0CrawlStatusSuccess     BookmarkContent0CrawlStatus = "success"
)

// Defines values for BookmarkContent0PreferredPreview.
const (
	BookmarkContent0PreferredPreviewLessThannil BookmarkContent0PreferredPreview = "<nil>"
	BookmarkContent0PreferredPreviewOverview    BookmarkContent0PreferredPreview = "overview"
	BookmarkContent0PreferredPreviewReaderView  BookmarkContent0PreferredPreview = "reader_view"
	BookmarkContent0PreferredPreviewScreenshot  BookmarkContent0PreferredPreview = "screenshot"
)

// Defines values for BookmarkContent0ReaderViewStatus.
const (
	BookmarkContent0ReaderViewStatusLessThannil BookmarkContent0ReaderViewStatus = "<nil>"
	BookmarkContent0ReaderViewStatusNotReadable BookmarkContent0ReaderViewStatus = "not_readable"
	BookmarkContent0ReaderViewStatusReadable    BookmarkContent0ReaderViewStatus = "readable"
	BookmarkContent0ReaderViewStatusUnavailable BookmarkContent0ReaderViewStatus = "unavailable"
	BookmarkContent0ReaderViewStatusUncertain   BookmarkContent0ReaderViewStatus = "uncertain"
)

// Defines values for BookmarkContent0Type.
const (
	BookmarkContent0TypeLink BookmarkContent0Type = "link"
)

// Defines values for BookmarkContent1Type.
const (
	BookmarkContent1TypeText BookmarkContent1Type = "text"
)

// Defines values for BookmarkContent2AssetType.
const (
	BookmarkContent2AssetTypeImage BookmarkContent2AssetType = "image"
	BookmarkContent2AssetTypePdf   BookmarkContent2AssetType = "pdf"
)

// Defines values for BookmarkContent2Type.
const (
	BookmarkContent2TypeAsset BookmarkContent2Type = "asset"
)

// Defines values for BookmarkContent3Type.
const (
	BookmarkContent3TypeUnknown BookmarkContent3Type = "unknown"
)

// Defines values for BookmarkEmbeddingStatus.
const (
	BookmarkEmbeddingStatusFailure     BookmarkEmbeddingStatus = "failure"
	BookmarkEmbeddingStatusLessThannil BookmarkEmbeddingStatus = "<nil>"
	BookmarkEmbeddingStatusPending     BookmarkEmbeddingStatus = "pending"
	BookmarkEmbeddingStatusSuccess     BookmarkEmbeddingStatus = "success"
)

// Defines values for BookmarkSource.
const (
	BookmarkSourceApi         BookmarkSource = "api"
	BookmarkSourceCli         BookmarkSource = "cli"
	BookmarkSourceExtension   BookmarkSource = "extension"
	BookmarkSourceImport      BookmarkSource = "import"
	BookmarkSourceLessThannil BookmarkSource = "<nil>"
	BookmarkSourceMobile      BookmarkSource = "mobile"
	BookmarkSourceRss         BookmarkSource = "rss"
	BookmarkSourceSinglefile  BookmarkSource = "singlefile"
	BookmarkSourceWeb         BookmarkSource = "web"
)

// Defines values for BookmarkSummarizationStatus.
const (
	BookmarkSummarizationStatusFailure     BookmarkSummarizationStatus = "failure"
	BookmarkSummarizationStatusLessThannil BookmarkSummarizationStatus = "<nil>"
	BookmarkSummarizationStatusPending     BookmarkSummarizationStatus = "pending"
	BookmarkSummarizationStatusSuccess     BookmarkSummarizationStatus = "success"
)

// Defines values for BookmarkTaggingStatus.
const (
	BookmarkTaggingStatusFailure     BookmarkTaggingStatus = "failure"
	BookmarkTaggingStatusLessThannil BookmarkTaggingStatus = "<nil>"
	BookmarkTaggingStatusPending     BookmarkTaggingStatus = "pending"
	BookmarkTaggingStatusSuccess     BookmarkTaggingStatus = "success"
)

// Defines values for BookmarkTagsAttachedBy.
const (
	BookmarkTagsAttachedByAi    BookmarkTagsAttachedBy = "ai"
	BookmarkTagsAttachedByHuman BookmarkTagsAttachedBy = "human"
)

// Defines values for BookmarkReadableContentBookmarkType.
const (
	BookmarkReadableContentBookmarkTypeAsset BookmarkReadableContentBookmarkType = "asset"
	BookmarkReadableContentBookmarkTypeLink  BookmarkReadableContentBookmarkType = "link"
	BookmarkReadableContentBookmarkTypeText  BookmarkReadableContentBookmarkType = "text"
)

// Defines values for BookmarkReadableContentFormat.
const (
	BookmarkReadableContentFormatMarkdown BookmarkReadableContentFormat = "markdown"
	BookmarkReadableContentFormatText     BookmarkReadableContentFormat = "text"
)

// Defines values for FeedLastFetchedStatus.
const (
	FeedLastFetchedStatusFailure     FeedLastFetchedStatus = "failure"
	FeedLastFetchedStatusLessThannil FeedLastFetchedStatus = "<nil>"
	FeedLastFetchedStatusPending     FeedLastFetchedStatus = "pending"
	FeedLastFetchedStatusSuccess     FeedLastFetchedStatus = "success"
)

// Defines values for HighlightColor.
const (
	HighlightColorBlue   HighlightColor = "blue"
	HighlightColorGreen  HighlightColor = "green"
	HighlightColorRed    HighlightColor = "red"
	HighlightColorYellow HighlightColor = "yellow"
)

// Defines values for ListType.
const (
	ListTypeManual ListType = "manual"
	ListTypeSmart  ListType = "smart"
)

// Defines values for ListUserRole.
const (
	Editor ListUserRole = "editor"
	Owner  ListUserRole = "owner"
	Public ListUserRole = "public"
	Viewer ListUserRole = "viewer"
)

// Defines values for AdminTriggerInferenceJSONBodyStatus.
const (
	AdminTriggerInferenceJSONBodyStatusAll     AdminTriggerInferenceJSONBodyStatus = "all"
	AdminTriggerInferenceJSONBodyStatusFailure AdminTriggerInferenceJSONBodyStatus = "failure"
	AdminTriggerInferenceJSONBodyStatusPending AdminTriggerInferenceJSONBodyStatus = "pending"
	AdminTriggerInferenceJSONBodyStatusSuccess AdminTriggerInferenceJSONBodyStatus = "success"
)

// Defines values for AdminTriggerInferenceJSONBodyType.
const (
	AdminTriggerInferenceJSONBodyTypeSummarize AdminTriggerInferenceJSONBodyType = "summarize"
	AdminTriggerInferenceJSONBodyTypeTag       AdminTriggerInferenceJSONBodyType = "tag"
)

// Defines values for AdminTriggerRecrawlJSONBodyCrawlStatus.
const (
	All     AdminTriggerRecrawlJSONBodyCrawlStatus = "all"
	Failure AdminTriggerRecrawlJSONBodyCrawlStatus = "failure"
	Pending AdminTriggerRecrawlJSONBodyCrawlStatus = "pending"
	Success AdminTriggerRecrawlJSONBodyCrawlStatus = "success"
)

// Defines values for AdminUpdateUserJSONBodyRole.
const (
	Admin AdminUpdateUserJSONBodyRole = "admin"
	User  AdminUpdateUserJSONBodyRole = "user"
)

// Defines values for ListBookmarksParamsSortOrder.
const (
	ListBookmarksParamsSortOrderAsc  ListBookmarksParamsSortOrder = "asc"
	ListBookmarksParamsSortOrderDesc ListBookmarksParamsSortOrder = "desc"
)

// Defines values for CreateBookmarkJSONBodyCrawlPriority.
const (
	Low    CreateBookmarkJSONBodyCrawlPriority = "low"
	Normal CreateBookmarkJSONBodyCrawlPriority = "normal"
)

// Defines values for CreateBookmarkJSONBodySource.
const (
	Api        CreateBookmarkJSONBodySource = "api"
	Cli        CreateBookmarkJSONBodySource = "cli"
	Extension  CreateBookmarkJSONBodySource = "extension"
	Import     CreateBookmarkJSONBodySource = "import"
	Mobile     CreateBookmarkJSONBodySource = "mobile"
	Rss        CreateBookmarkJSONBodySource = "rss"
	Singlefile CreateBookmarkJSONBodySource = "singlefile"
	Web        CreateBookmarkJSONBodySource = "web"
)

// Defines values for CreateBookmarkJSONBody0Type.
const (
	Link CreateBookmarkJSONBody0Type = "link"
)

// Defines values for CreateBookmarkJSONBody1Type.
const (
	CreateBookmarkJSONBody1TypeText CreateBookmarkJSONBody1Type = "text"
)

// Defines values for CreateBookmarkJSONBody2AssetType.
const (
	CreateBookmarkJSONBody2AssetTypeImage CreateBookmarkJSONBody2AssetType = "image"
	CreateBookmarkJSONBody2AssetTypePdf   CreateBookmarkJSONBody2AssetType = "pdf"
)

// Defines values for CreateBookmarkJSONBody2Type.
const (
	CreateBookmarkJSONBody2TypeAsset CreateBookmarkJSONBody2Type = "asset"
)

// Defines values for SearchBookmarksParamsSearchMode.
const (
	Fts      SearchBookmarksParamsSearchMode = "fts"
	Hybrid   SearchBookmarksParamsSearchMode = "hybrid"
	Semantic SearchBookmarksParamsSearchMode = "semantic"
)

// Defines values for SearchBookmarksParamsSortOrder.
const (
	SearchBookmarksParamsSortOrderAsc       SearchBookmarksParamsSortOrder = "asc"
	SearchBookmarksParamsSortOrderDesc      SearchBookmarksParamsSortOrder = "desc"
	SearchBookmarksParamsSortOrderRelevance SearchBookmarksParamsSortOrder = "relevance"
)

// Defines values for AttachAssetToBookmarkJSONBodyAssetType.
const (
	AttachAssetToBookmarkJSONBodyAssetTypeAssetScreenshot   AttachAssetToBookmarkJSONBodyAssetType = "assetScreenshot"
	AttachAssetToBookmarkJSONBodyAssetTypeAvatar            AttachAssetToBookmarkJSONBodyAssetType = "avatar"
	AttachAssetToBookmarkJSONBodyAssetTypeBannerImage       AttachAssetToBookmarkJSONBodyAssetType = "bannerImage"
	AttachAssetToBookmarkJSONBodyAssetTypeBookmarkAsset     AttachAssetToBookmarkJSONBodyAssetType = "bookmarkAsset"
	AttachAssetToBookmarkJSONBodyAssetTypeFullPageArchive   AttachAssetToBookmarkJSONBodyAssetType = "fullPageArchive"
	AttachAssetToBookmarkJSONBodyAssetTypeLinkHtmlContent   AttachAssetToBookmarkJSONBodyAssetType = "linkHtmlContent"
	AttachAssetToBookmarkJSONBodyAssetTypePdf               AttachAssetToBookmarkJSONBodyAssetType = "pdf"
	AttachAssetToBookmarkJSONBodyAssetTypePrecrawledArchive AttachAssetToBookmarkJSONBodyAssetType = "precrawledArchive"
	AttachAssetToBookmarkJSONBodyAssetTypeScreenshot        AttachAssetToBookmarkJSONBodyAssetType = "screenshot"
	AttachAssetToBookmarkJSONBodyAssetTypeUnknown           AttachAssetToBookmarkJSONBodyAssetType = "unknown"
	AttachAssetToBookmarkJSONBodyAssetTypeUserUploaded      AttachAssetToBookmarkJSONBodyAssetType = "userUploaded"
	AttachAssetToBookmarkJSONBodyAssetTypeVideo             AttachAssetToBookmarkJSONBodyAssetType = "video"
)

// Defines values for GetBookmarkReadableContentParamsFormat.
const (
	GetBookmarkReadableContentParamsFormatMarkdown GetBookmarkReadableContentParamsFormat = "markdown"
	GetBookmarkReadableContentParamsFormatText     GetBookmarkReadableContentParamsFormat = "text"
)

// Defines values for DetachTagsFromBookmarkJSONBodyTagsAttachedBy.
const (
	DetachTagsFromBookmarkJSONBodyTagsAttachedByAi    DetachTagsFromBookmarkJSONBodyTagsAttachedBy = "ai"
	DetachTagsFromBookmarkJSONBodyTagsAttachedByHuman DetachTagsFromBookmarkJSONBodyTagsAttachedBy = "human"
)

// Defines values for AttachTagsToBookmarkJSONBodyTagsAttachedBy.
const (
	AttachTagsToBookmarkJSONBodyTagsAttachedByAi    AttachTagsToBookmarkJSONBodyTagsAttachedBy = "ai"
	AttachTagsToBookmarkJSONBodyTagsAttachedByHuman AttachTagsToBookmarkJSONBodyTagsAttachedBy = "human"
)

// Defines values for CreateHighlightJSONBodyColor.
const (
	CreateHighlightJSONBodyColorBlue   CreateHighlightJSONBodyColor = "blue"
	CreateHighlightJSONBodyColorGreen  CreateHighlightJSONBodyColor = "green"
	CreateHighlightJSONBodyColorRed    CreateHighlightJSONBodyColor = "red"
	CreateHighlightJSONBodyColorYellow CreateHighlightJSONBodyColor = "yellow"
)

// Defines values for UpdateHighlightJSONBodyColor.
const (
	Blue   UpdateHighlightJSONBodyColor = "blue"
	Green  UpdateHighlightJSONBodyColor = "green"
	Red    UpdateHighlightJSONBodyColor = "red"
	Yellow UpdateHighlightJSONBodyColor = "yellow"
)

// Defines values for CreateListJSONBodyType.
const (
	CreateListJSONBodyTypeManual CreateListJSONBodyType = "manual"
	CreateListJSONBodyTypeSmart  CreateListJSONBodyType = "smart"
)

// Defines values for GetListBookmarksParamsSortOrder.
const (
	GetListBookmarksParamsSortOrderAsc  GetListBookmarksParamsSortOrder = "asc"
	GetListBookmarksParamsSortOrderDesc GetListBookmarksParamsSortOrder = "desc"
)

// Defines values for ListTagsParamsSort.
const (
	Name      ListTagsParamsSort = "name"
	Relevance ListTagsParamsSort = "relevance"
	Usage     ListTagsParamsSort = "usage"
)

// Defines values for ListTagsParamsAttachedBy.
const (
	ListTagsParamsAttachedByAi    ListTagsParamsAttachedBy = "ai"
	ListTagsParamsAttachedByHuman ListTagsParamsAttachedBy = "human"
	ListTagsParamsAttachedByNone  ListTagsParamsAttachedBy = "none"
)

// Defines values for GetTagBookmarksParamsSortOrder.
const (
	GetTagBookmarksParamsSortOrderAsc  GetTagBookmarksParamsSortOrder = "asc"
	GetTagBookmarksParamsSortOrderDesc GetTagBookmarksParamsSortOrder = "desc"
)

// AssetId The unique identifier of the asset.
type AssetId = string

// BackupId The unique identifier of the backup.
type BackupId = string

// Bookmark defines model for Bookmark.
type Bookmark struct {
	Archived bool `json:"archived"`
	Assets   []struct {
		AssetType BookmarkAssetsAssetType `json:"assetType"`
		FileName  *string                 `json:"fileName"`
		Id        string                  `json:"id"`
	} `json:"assets"`
	Content             Bookmark_Content             `json:"content"`
	CreatedAt           time.Time                    `json:"createdAt"`
	EmbeddingStatus     *BookmarkEmbeddingStatus     `json:"embeddingStatus"`
	Favourited          bool                         `json:"favourited"`
	FirstCreatedAt      *time.Time                   `json:"firstCreatedAt,omitempty"`
	Id                  string                       `json:"id"`
	ModifiedAt          *time.Time                   `json:"modifiedAt"`
	Note                *string                      `json:"note"`
	Source              *BookmarkSource              `json:"source"`
	SummarizationStatus *BookmarkSummarizationStatus `json:"summarizationStatus"`
	Summary             *string                      `json:"summary"`
	TaggingStatus       *BookmarkTaggingStatus       `json:"taggingStatus"`
	Tags                []struct {
		AttachedBy BookmarkTagsAttachedBy `json:"attachedBy"`
		Id         string                 `json:"id"`
		Name       string                 `json:"name"`
	} `json:"tags"`
	Title  *string `json:"title"`
	UserId string  `json:"userId"`
}

// BookmarkAssetsAssetType defines model for Bookmark.Assets.AssetType.
type BookmarkAssetsAssetType string

// BookmarkContent0 defines model for .
type BookmarkContent0 struct {
	Author                   *string                           `json:"author"`
	ContentAssetId           *string                           `json:"contentAssetId"`
	CrawlStatus              *BookmarkContent0CrawlStatus      `json:"crawlStatus"`
	CrawledAt                *time.Time                        `json:"crawledAt"`
	DateModified             *time.Time                        `json:"dateModified"`
	DatePublished            *time.Time                        `json:"datePublished"`
	Description              *string                           `json:"description"`
	Favicon                  *string                           `json:"favicon"`
	FullPageArchiveAssetId   *string                           `json:"fullPageArchiveAssetId"`
	HtmlContent              *string                           `json:"htmlContent"`
	ImageAssetId             *string                           `json:"imageAssetId"`
	ImageUrl                 *string                           `json:"imageUrl"`
	PdfAssetId               *string                           `json:"pdfAssetId"`
	PrecrawledArchiveAssetId *string                           `json:"precrawledArchiveAssetId"`
	PreferredPreview         *BookmarkContent0PreferredPreview `json:"preferredPreview"`
	Publisher                *string                           `json:"publisher"`
	ReaderViewScore          *int                              `json:"readerViewScore"`
	ReaderViewStatus         *BookmarkContent0ReaderViewStatus `json:"readerViewStatus"`
	ScreenshotAssetId        *string                           `json:"screenshotAssetId"`
	Title                    *string                           `json:"title"`
	Type                     BookmarkContent0Type              `json:"type"`
	Url                      string                            `json:"url"`
	VideoAssetId             *string                           `json:"videoAssetId"`
}

// BookmarkContent0CrawlStatus defines model for Bookmark.Content.0.CrawlStatus.
type BookmarkContent0CrawlStatus string

// BookmarkContent0PreferredPreview defines model for Bookmark.Content.0.PreferredPreview.
type BookmarkContent0PreferredPreview string

// BookmarkContent0ReaderViewStatus defines model for Bookmark.Content.0.ReaderViewStatus.
type BookmarkContent0ReaderViewStatus string

// BookmarkContent0Type defines model for Bookmark.Content.0.Type.
type BookmarkContent0Type string

// BookmarkContent1 defines model for .
type BookmarkContent1 struct {
	SourceUrl *string              `json:"sourceUrl"`
	Text      string               `json:"text"`
	Type      BookmarkContent1Type `json:"type"`
}

// BookmarkContent1Type defines model for Bookmark.Content.1.Type.
type BookmarkContent1Type string

// BookmarkContent2 defines model for .
type BookmarkContent2 struct {
	AssetId   string                    `json:"assetId"`
	AssetType BookmarkContent2AssetType `json:"assetType"`
	Content   *string                   `json:"content"`
	FileName  *string                   `json:"fileName"`
	Size      *float32                  `json:"size"`
	SourceUrl *string                   `json:"sourceUrl"`
	Type      BookmarkContent2Type      `json:"type"`
}

// BookmarkContent2AssetType defines model for Bookmark.Content.2.AssetType.
type BookmarkContent2AssetType string

// BookmarkContent2Type defines model for Bookmark.Content.2.Type.
type BookmarkContent2Type string

// BookmarkContent3 defines model for .
type BookmarkContent3 struct {
	Type BookmarkContent3Type `json:"type"`
}

// BookmarkContent3Type defines model for Bookmark.Content.3.Type.
type BookmarkContent3Type string

// Bookmark_Content defines model for Bookmark.Content.
type Bookmark_Content struct {
	union json.RawMessage
}

// BookmarkEmbeddingStatus defines model for Bookmark.EmbeddingStatus.
type BookmarkEmbeddingStatus string

// BookmarkSource defines model for Bookmark.Source.
type BookmarkSource string

// BookmarkSummarizationStatus defines model for Bookmark.SummarizationStatus.
type BookmarkSummarizationStatus string

// BookmarkTaggingStatus defines model for Bookmark.TaggingStatus.
type BookmarkTaggingStatus string

// BookmarkTagsAttachedBy defines model for Bookmark.Tags.AttachedBy.
type BookmarkTagsAttachedBy string

// BookmarkId The unique identifier of the bookmark.
type BookmarkId = string

// BookmarkReadableContent defines model for BookmarkReadableContent.
type BookmarkReadableContent struct {
	BookmarkId   string                              `json:"bookmarkId"`
	BookmarkType BookmarkReadableContentBookmarkType `json:"bookmarkType"`
	Content      string                              `json:"content"`

	// ContentVersion A hash identifying the rendered content version used by this cursor.
	ContentVersion string                        `json:"contentVersion"`
	Format         BookmarkReadableContentFormat `json:"format"`

	// NextCursor Cursor for the next chunk, or null when all content has been returned.
	NextCursor *string `json:"nextCursor"`
	Range      struct {
		// End Zero-based end offset in Unicode characters, exclusive.
		End int `json:"end"`

		// Start Zero-based start offset in Unicode characters, inclusive.
		Start int `json:"start"`

		// Total Total number of Unicode characters in the rendered content.
		Total int `json:"total"`
	} `json:"range"`

	// Truncated Whether more readable content remains after this chunk.
	Truncated bool `json:"truncated"`
}

// BookmarkReadableContentBookmarkType defines model for BookmarkReadableContent.BookmarkType.
type BookmarkReadableContentBookmarkType string

// BookmarkReadableContentFormat defines model for BookmarkReadableContent.Format.
type BookmarkReadableContentFormat string

// Cursor Cursor from a previous response to fetch the next page.
type Cursor = string

// Error defines model for Error.
type Error struct {
	// Code A machine-readable error code.
	Code string `json:"code"`

	// Message A human-readable error message.
	Message string `json:"message"`
}

// Feed defines model for Feed.
type Feed struct {
	Enabled    bool   `json:"enabled"`
	Id         string `json:"id"`
	ImportTags bool   `json:"importTags"`

	// LastFetchedAt ISO 8601 timestamp of the last fetch attempt, or null if never fetched.
	LastFetchedAt     *string                `json:"lastFetchedAt"`
	LastFetchedStatus *FeedLastFetchedStatus `json:"lastFetchedStatus"`

	// LastSuccessfulFetchAt ISO 8601 timestamp of the last successful fetch, or null if the feed has never been fetched successfully.
	LastSuccessfulFetchAt *string `json:"lastSuccessfulFetchAt"`
	Name                  string  `json:"name"`
	Url                   string  `json:"url"`
}

// FeedLastFetchedStatus defines model for Feed.LastFetchedStatus.
type FeedLastFetchedStatus string

// FeedId The unique identifier of the feed.
type FeedId = string

// Highlight defines model for Highlight.
type Highlight struct {
	BookmarkId  string          `json:"bookmarkId"`
	Color       *HighlightColor `json:"color,omitempty"`
	CreatedAt   time.Time       `json:"createdAt"`
	EndOffset   float32         `json:"endOffset"`
	Id          string          `json:"id"`
	Note        *string         `json:"note"`
	StartOffset float32         `json:"startOffset"`
	Text        *string         `json:"text"`
	UserId      string          `json:"userId"`
}

// HighlightColor defines model for Highlight.Color.
type HighlightColor string

// HighlightId The unique identifier of the highlight.
type HighlightId = string

// List defines model for List.
type List struct {
	Description      *string      `json:"description"`
	HasCollaborators bool         `json:"hasCollaborators"`
	Icon             string       `json:"icon"`
	Id               string       `json:"id"`
	Name             string       `json:"name"`
	ParentId         *string      `json:"parentId"`
	Public           bool         `json:"public"`
	Query            *string      `json:"query"`
	Type             *ListType    `json:"type,omitempty"`
	UserRole         ListUserRole `json:"userRole"`
}

// ListType defines model for List.Type.
type ListType string

// ListUserRole defines model for List.UserRole.
type ListUserRole string

// ListId The unique identifier of the list.
type ListId = string

// PaginatedBookmarks defines model for PaginatedBookmarks.
type PaginatedBookmarks struct {
	Bookmarks []Bookmark `json:"bookmarks"`

	// NextCursor Cursor for the next page, or null if no more results.
	NextCursor *string `json:"nextCursor"`
}

// PaginatedHighlights defines model for PaginatedHighlights.
type PaginatedHighlights struct {
	Highlights []Highlight `json:"highlights"`

	// NextCursor Cursor for the next page, or null if no more results.
	NextCursor *string `json:"nextCursor"`
}

// SignedAssetUrl defines model for SignedAssetUrl.
type SignedAssetUrl struct {
	// AssetId The unique identifier of the asset.
	AssetId string `json:"assetId"`

	// ExpiresAt When the signed URL expires, in ISO 8601 format.
	ExpiresAt time.Time `json:"expiresAt"`

	// SignedUrl The temporary URL for downloading the asset.
	SignedUrl string `json:"signedUrl"`
}

// Tag defines model for Tag.
type Tag struct {
	Id                         string  `json:"id"`
	Name                       string  `json:"name"`
	NumBookmarks               float32 `json:"numBookmarks"`
	NumBookmarksByAttachedType struct {
		Ai    *float32 `json:"ai,omitempty"`
		Human *float32 `json:"human,omitempty"`
	} `json:"numBookmarksByAttachedType"`
}

// TagId The unique identifier of the tag.
type TagId = string

// UploadedAsset defines model for UploadedAsset.
type UploadedAsset struct {
	// AssetId The unique identifier assigned to the uploaded asset.
	AssetId string `json:"assetId"`

	// ContentType The MIME type of the uploaded file.
	ContentType string `json:"contentType"`

	// FileName The original file name of the uploaded file.
	FileName string `json:"fileName"`

	// Size The size of the uploaded file in bytes.
	Size float32 `json:"size"`
}

// AdminTriggerInferenceJSONBody defines parameters for AdminTriggerInference.
type AdminTriggerInferenceJSONBody struct {
	// ModifiedWithinSeconds Only process bookmarks modified within this many seconds. Omit to process all matching bookmarks.
	ModifiedWithinSeconds *int `json:"modifiedWithinSeconds,omitempty"`

	// Status Filter bookmarks by their inference status. Use 'failure' to retry only failed ones.
	Status *AdminTriggerInferenceJSONBodyStatus `json:"status,omitempty"`

	// Type The type of inference to run: 'tag' for AI tagging, 'summarize' for AI summarization.
	Type AdminTriggerInferenceJSONBodyType `json:"type"`
}

// AdminTriggerInferenceJSONBodyStatus defines parameters for AdminTriggerInference.
type AdminTriggerInferenceJSONBodyStatus string

// AdminTriggerInferenceJSONBodyType defines parameters for AdminTriggerInference.
type AdminTriggerInferenceJSONBodyType string

// AdminTriggerRecrawlJSONBody defines parameters for AdminTriggerRecrawl.
type AdminTriggerRecrawlJSONBody struct {
	// CrawlStatus Filter bookmarks by their crawl status. Use 'failure' to retry only failed crawls.
	CrawlStatus *AdminTriggerRecrawlJSONBodyCrawlStatus `json:"crawlStatus,omitempty"`

	// ModifiedWithinSeconds Only process bookmarks modified within this many seconds. Omit to process all matching bookmarks.
	ModifiedWithinSeconds *int `json:"modifiedWithinSeconds,omitempty"`

	// RunInference Whether to run AI inference after crawling.
	RunInference *bool `json:"runInference,omitempty"`
}

// AdminTriggerRecrawlJSONBodyCrawlStatus defines parameters for AdminTriggerRecrawl.
type AdminTriggerRecrawlJSONBodyCrawlStatus string

// AdminTriggerReindexJSONBody defines parameters for AdminTriggerReindex.
type AdminTriggerReindexJSONBody struct {
	// ModifiedWithinSeconds Only process bookmarks modified within this many seconds. Omit to process all matching bookmarks.
	ModifiedWithinSeconds *int `json:"modifiedWithinSeconds,omitempty"`
}

// AdminUpdateUserJSONBody defines parameters for AdminUpdateUser.
type AdminUpdateUserJSONBody struct {
	BookmarkQuota          *int                         `json:"bookmarkQuota"`
	BrowserCrawlingEnabled *bool                        `json:"browserCrawlingEnabled"`
	Role                   *AdminUpdateUserJSONBodyRole `json:"role,omitempty"`
	StorageQuota           *int                         `json:"storageQuota"`
}

// AdminUpdateUserJSONBodyRole defines parameters for AdminUpdateUser.
type AdminUpdateUserJSONBodyRole string

// UploadAssetMultipartBody defines parameters for UploadAsset.
type UploadAssetMultipartBody struct {
	// File File to be uploaded
	File openapi_types.File `json:"file"`
}

// ListBookmarksParams defines parameters for ListBookmarks.
type ListBookmarksParams struct {
	// Archived Filter by archived status.
	Archived *bool `form:"archived,omitempty" json:"archived,omitempty"`

	// Favourited Filter by favourited status.
	Favourited *bool `form:"favourited,omitempty" json:"favourited,omitempty"`

	// SortOrder Sort order by creation date. Defaults to 'desc'.
	SortOrder *ListBookmarksParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *float32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor from a previous response to fetch the next page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// IncludeContent If set to true, the bookmark's full content (HTML, text, etc.) will be included in the response. Set to false for lighter responses when only metadata is needed.
	IncludeContent *bool `form:"includeContent,omitempty" json:"includeContent,omitempty"`
}

// ListBookmarksParamsSortOrder defines parameters for ListBookmarks.
type ListBookmarksParamsSortOrder string

// CreateBookmarkJSONBody defines parameters for CreateBookmark.
type CreateBookmarkJSONBody struct {
	Archived        *bool                                `json:"archived,omitempty"`
	CrawlPriority   *CreateBookmarkJSONBodyCrawlPriority `json:"crawlPriority,omitempty"`
	CreatedAt       *time.Time                           `json:"createdAt,omitempty"`
	Favourited      *bool                                `json:"favourited,omitempty"`
	ImportSessionId *string                              `json:"importSessionId,omitempty"`
	Note            *string                              `json:"note,omitempty"`
	Source          *CreateBookmarkJSONBodySource        `json:"source,omitempty"`
	Summary         *string                              `json:"summary,omitempty"`
	Title           *string                              `json:"title"`
	union           json.RawMessage
}

// CreateBookmarkJSONBodyCrawlPriority defines parameters for CreateBookmark.
type CreateBookmarkJSONBodyCrawlPriority string

// CreateBookmarkJSONBodySource defines parameters for CreateBookmark.
type CreateBookmarkJSONBodySource string

// CreateBookmarkJSONBody0 defines parameters for CreateBookmark.
type CreateBookmarkJSONBody0 struct {
	PrecrawledArchiveId *string                     `json:"precrawledArchiveId,omitempty"`
	Type                CreateBookmarkJSONBody0Type `json:"type"`
	Url                 string                      `json:"url"`
}

// CreateBookmarkJSONBody0Type defines parameters for CreateBookmark.
type CreateBookmarkJSONBody0Type string

// CreateBookmarkJSONBody1 defines parameters for CreateBookmark.
type CreateBookmarkJSONBody1 struct {
	SourceUrl *string                     `json:"sourceUrl,omitempty"`
	Text      string                      `json:"text"`
	Type      CreateBookmarkJSONBody1Type `json:"type"`
}

// CreateBookmarkJSONBody1Type defines parameters for CreateBookmark.
type CreateBookmarkJSONBody1Type string

// CreateBookmarkJSONBody2 defines parameters for CreateBookmark.
type CreateBookmarkJSONBody2 struct {
	AssetId   string                           `json:"assetId"`
	AssetType CreateBookmarkJSONBody2AssetType `json:"assetType"`
	FileName  *string                          `json:"fileName,omitempty"`
	SourceUrl *string                          `json:"sourceUrl,omitempty"`
	Type      CreateBookmarkJSONBody2Type      `json:"type"`
}

// CreateBookmarkJSONBody2AssetType defines parameters for CreateBookmark.
type CreateBookmarkJSONBody2AssetType string

// CreateBookmarkJSONBody2Type defines parameters for CreateBookmark.
type CreateBookmarkJSONBody2Type string

// CheckBookmarkUrlParams defines parameters for CheckBookmarkUrl.
type CheckBookmarkUrlParams struct {
	// Url The URL to check against existing bookmarks.
	Url string `form:"url" json:"url"`
}

// SearchBookmarksParams defines parameters for SearchBookmarks.
type SearchBookmarksParams struct {
	// Q The search query string.
	Q string `form:"q" json:"q"`

	// SearchMode Search strategy. 'fts' uses full-text search, 'semantic' uses bookmark embeddings, and 'hybrid' fuses a fixed candidate window from both. Hybrid falls back to full-text search when the query contains no free-text terms or when embedding infrastructure is unavailable. Semantic hits below a minimum similarity are dropped, so semantic search may return fewer results than requested.
	SearchMode *SearchBookmarksParamsSearchMode `form:"searchMode,omitempty" json:"searchMode,omitempty"`

	// SortOrder Sort order for results. Defaults to 'relevance'. Use 'asc' or 'desc' for date-based sorting.
	SortOrder *SearchBookmarksParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *float32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor from a previous response to fetch the next page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// IncludeContent If set to true, the bookmark's full content (HTML, text, etc.) will be included in the response. Set to false for lighter responses when only metadata is needed.
	IncludeContent *bool `form:"includeContent,omitempty" json:"includeContent,omitempty"`
}

// SearchBookmarksParamsSearchMode defines parameters for SearchBookmarks.
type SearchBookmarksParamsSearchMode string

// SearchBookmarksParamsSortOrder defines parameters for SearchBookmarks.
type SearchBookmarksParamsSortOrder string

// GetBookmarkParams defines parameters for GetBookmark.
type GetBookmarkParams struct {
	// IncludeContent If set to true, the bookmark's full content (HTML, text, etc.) will be included in the response. Set to false for lighter responses when only metadata is needed.
	IncludeContent *bool `form:"includeContent,omitempty" json:"includeContent,omitempty"`
}

// UpdateBookmarkJSONBody defines parameters for UpdateBookmark.
type UpdateBookmarkJSONBody struct {
	Archived      *bool      `json:"archived,omitempty"`
	AssetContent  *string    `json:"assetContent"`
	Author        *string    `json:"author"`
	CreatedAt     *time.Time `json:"createdAt,omitempty"`
	DateModified  *time.Time `json:"dateModified"`
	DatePublished *time.Time `json:"datePublished"`
	Description   *string    `json:"description"`
	Favourited    *bool      `json:"favourited,omitempty"`
	Note          *string    `json:"note,omitempty"`
	Publisher     *string    `json:"publisher"`
	Summary       *string    `json:"summary"`
	Text          *string    `json:"text"`
	Title         *string    `json:"title"`
	Url           *string    `json:"url,omitempty"`
}

// AttachAssetToBookmarkJSONBody defines parameters for AttachAssetToBookmark.
type AttachAssetToBookmarkJSONBody struct {
	// AssetType The type classification for this asset.
	AssetType AttachAssetToBookmarkJSONBodyAssetType `json:"assetType"`

	// Id The ID of the previously uploaded asset.
	Id string `json:"id"`
}

// AttachAssetToBookmarkJSONBodyAssetType defines parameters for AttachAssetToBookmark.
type AttachAssetToBookmarkJSONBodyAssetType string

// ReplaceAssetOnBookmarkJSONBody defines parameters for ReplaceAssetOnBookmark.
type ReplaceAssetOnBookmarkJSONBody struct {
	// AssetId The ID of the new asset to use as a replacement.
	AssetId string `json:"assetId"`
}

// GetBookmarkReadableContentParams defines parameters for GetBookmarkReadableContent.
type GetBookmarkReadableContentParams struct {
	// Format The readable representation. If omitted with a cursor, the cursor's format is used; otherwise defaults to markdown.
	Format *GetBookmarkReadableContentParamsFormat `form:"format,omitempty" json:"format,omitempty"`

	// MaxChars Maximum number of Unicode characters to return. The chunk may end earlier at a paragraph or line boundary.
	MaxChars *int `form:"maxChars,omitempty" json:"maxChars,omitempty"`

	// Cursor Opaque continuation cursor returned as `nextCursor` by a previous response.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetBookmarkReadableContentParamsFormat defines parameters for GetBookmarkReadableContent.
type GetBookmarkReadableContentParamsFormat string

// DetachTagsFromBookmarkJSONBody defines parameters for DetachTagsFromBookmark.
type DetachTagsFromBookmarkJSONBody struct {
	Tags []struct {
		AttachedBy *DetachTagsFromBookmarkJSONBodyTagsAttachedBy `json:"attachedBy,omitempty"`
		TagId      *string                                       `json:"tagId,omitempty"`
		TagName    *string                                       `json:"tagName,omitempty"`
	} `json:"tags"`
}

// DetachTagsFromBookmarkJSONBodyTagsAttachedBy defines parameters for DetachTagsFromBookmark.
type DetachTagsFromBookmarkJSONBodyTagsAttachedBy string

// AttachTagsToBookmarkJSONBody defines parameters for AttachTagsToBookmark.
type AttachTagsToBookmarkJSONBody struct {
	Tags []struct {
		AttachedBy *AttachTagsToBookmarkJSONBodyTagsAttachedBy `json:"attachedBy,omitempty"`
		TagId      *string                                     `json:"tagId,omitempty"`
		TagName    *string                                     `json:"tagName,omitempty"`
	} `json:"tags"`
}

// AttachTagsToBookmarkJSONBodyTagsAttachedBy defines parameters for AttachTagsToBookmark.
type AttachTagsToBookmarkJSONBodyTagsAttachedBy string

// CreateFeedJSONBody defines parameters for CreateFeed.
type CreateFeedJSONBody struct {
	Enabled    bool   `json:"enabled"`
	ImportTags *bool  `json:"importTags,omitempty"`
	Name       string `json:"name"`
	Url        string `json:"url"`
}

// UpdateFeedJSONBody defines parameters for UpdateFeed.
type UpdateFeedJSONBody struct {
	Enabled    *bool   `json:"enabled,omitempty"`
	ImportTags *bool   `json:"importTags,omitempty"`
	Name       *string `json:"name,omitempty"`
	Url        *string `json:"url,omitempty"`
}

// ListHighlightsParams defines parameters for ListHighlights.
type ListHighlightsParams struct {
	// Limit Maximum number of items to return per page.
	Limit *float32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor from a previous response to fetch the next page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateHighlightJSONBody defines parameters for CreateHighlight.
type CreateHighlightJSONBody struct {
	BookmarkId  string                        `json:"bookmarkId"`
	Color       *CreateHighlightJSONBodyColor `json:"color,omitempty"`
	EndOffset   float32                       `json:"endOffset"`
	Note        *string                       `json:"note"`
	StartOffset float32                       `json:"startOffset"`
	Text        *string                       `json:"text"`
}

// CreateHighlightJSONBodyColor defines parameters for CreateHighlight.
type CreateHighlightJSONBodyColor string

// UpdateHighlightJSONBody defines parameters for UpdateHighlight.
type UpdateHighlightJSONBody struct {
	Color *UpdateHighlightJSONBodyColor `json:"color,omitempty"`
	Note  *string                       `json:"note"`
}

// UpdateHighlightJSONBodyColor defines parameters for UpdateHighlight.
type UpdateHighlightJSONBodyColor string

// CreateListJSONBody defines parameters for CreateList.
type CreateListJSONBody struct {
	Description *string                 `json:"description,omitempty"`
	Icon        string                  `json:"icon"`
	Name        string                  `json:"name"`
	ParentId    *string                 `json:"parentId"`
	Query       *string                 `json:"query,omitempty"`
	Type        *CreateListJSONBodyType `json:"type,omitempty"`
}

// CreateListJSONBodyType defines parameters for CreateList.
type CreateListJSONBodyType string

// UpdateListJSONBody defines parameters for UpdateList.
type UpdateListJSONBody struct {
	Description *string `json:"description"`
	Icon        *string `json:"icon,omitempty"`
	Name        *string `json:"name,omitempty"`
	ParentId    *string `json:"parentId"`
	Public      *bool   `json:"public,omitempty"`
	Query       *string `json:"query,omitempty"`
}

// GetListBookmarksParams defines parameters for GetListBookmarks.
type GetListBookmarksParams struct {
	// SortOrder Sort order by creation date. Defaults to 'desc'.
	SortOrder *GetListBookmarksParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *float32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor from a previous response to fetch the next page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// IncludeContent If set to true, the bookmark's full content (HTML, text, etc.) will be included in the response. Set to false for lighter responses when only metadata is needed.
	IncludeContent *bool `form:"includeContent,omitempty" json:"includeContent,omitempty"`
}

// GetListBookmarksParamsSortOrder defines parameters for GetListBookmarks.
type GetListBookmarksParamsSortOrder string

// ListTagsParams defines parameters for ListTags.
type ListTagsParams struct {
	NameContains *string                   `form:"nameContains,omitempty" json:"nameContains,omitempty"`
	Sort         *ListTagsParamsSort       `form:"sort,omitempty" json:"sort,omitempty"`
	AttachedBy   *ListTagsParamsAttachedBy `form:"attachedBy,omitempty" json:"attachedBy,omitempty"`
	Cursor       *string                   `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit        *float32                  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListTagsParamsSort defines parameters for ListTags.
type ListTagsParamsSort string

// ListTagsParamsAttachedBy defines parameters for ListTags.
type ListTagsParamsAttachedBy string

// CreateTagJSONBody defines parameters for CreateTag.
type CreateTagJSONBody struct {
	Name string `json:"name"`
}

// UpdateTagJSONBody defines parameters for UpdateTag.
type UpdateTagJSONBody struct {
	Name *string `json:"name,omitempty"`
}

// GetTagBookmarksParams defines parameters for GetTagBookmarks.
type GetTagBookmarksParams struct {
	// SortOrder Sort order by creation date. Defaults to 'desc'.
	SortOrder *GetTagBookmarksParamsSortOrder `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *float32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor from a previous response to fetch the next page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// IncludeContent If set to true, the bookmark's full content (HTML, text, etc.) will be included in the response. Set to false for lighter responses when only metadata is needed.
	IncludeContent *bool `form:"includeContent,omitempty" json:"includeContent,omitempty"`
}

// GetTagBookmarksParamsSortOrder defines parameters for GetTagBookmarks.
type GetTagBookmarksParamsSortOrder string

// AdminTriggerInferenceJSONRequestBody defines body for AdminTriggerInference for application/json ContentType.
type AdminTriggerInferenceJSONRequestBody AdminTriggerInferenceJSONBody

// AdminTriggerRecrawlJSONRequestBody defines body for AdminTriggerRecrawl for application/json ContentType.
type AdminTriggerRecrawlJSONRequestBody AdminTriggerRecrawlJSONBody

// AdminTriggerReindexJSONRequestBody defines body for AdminTriggerReindex for application/json ContentType.
type AdminTriggerReindexJSONRequestBody AdminTriggerReindexJSONBody

// AdminUpdateUserJSONRequestBody defines body for AdminUpdateUser for application/json ContentType.
type AdminUpdateUserJSONRequestBody AdminUpdateUserJSONBody

// UploadAssetMultipartRequestBody defines body for UploadAsset for multipart/form-data ContentType.
type UploadAssetMultipartRequestBody UploadAssetMultipartBody

// CreateBookmarkJSONRequestBody defines body for CreateBookmark for application/json ContentType.
type CreateBookmarkJSONRequestBody CreateBookmarkJSONBody

// UpdateBookmarkJSONRequestBody defines body for UpdateBookmark for application/json ContentType.
type UpdateBookmarkJSONRequestBody UpdateBookmarkJSONBody

// AttachAssetToBookmarkJSONRequestBody defines body for AttachAssetToBookmark for application/json ContentType.
type AttachAssetToBookmarkJSONRequestBody AttachAssetToBookmarkJSONBody

// ReplaceAssetOnBookmarkJSONRequestBody defines body for ReplaceAssetOnBookmark for application/json ContentType.
type ReplaceAssetOnBookmarkJSONRequestBody ReplaceAssetOnBookmarkJSONBody

// DetachTagsFromBookmarkJSONRequestBody defines body for DetachTagsFromBookmark for application/json ContentType.
type DetachTagsFromBookmarkJSONRequestBody DetachTagsFromBookmarkJSONBody

// AttachTagsToBookmarkJSONRequestBody defines body for AttachTagsToBookmark for application/json ContentType.
type AttachTagsToBookmarkJSONRequestBody AttachTagsToBookmarkJSONBody

// CreateFeedJSONRequestBody defines body for CreateFeed for application/json ContentType.
type CreateFeedJSONRequestBody CreateFeedJSONBody

// UpdateFeedJSONRequestBody defines body for UpdateFeed for application/json ContentType.
type UpdateFeedJSONRequestBody UpdateFeedJSONBody

// CreateHighlightJSONRequestBody defines body for CreateHighlight for application/json ContentType.
type CreateHighlightJSONRequestBody CreateHighlightJSONBody

// UpdateHighlightJSONRequestBody defines body for UpdateHighlight for application/json ContentType.
type UpdateHighlightJSONRequestBody UpdateHighlightJSONBody

// CreateListJSONRequestBody defines body for CreateList for application/json ContentType.
type CreateListJSONRequestBody CreateListJSONBody

// UpdateListJSONRequestBody defines body for UpdateList for application/json ContentType.
type UpdateListJSONRequestBody UpdateListJSONBody

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody CreateTagJSONBody

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody UpdateTagJSONBody

// AsBookmarkContent0 returns the union data inside the Bookmark_Content as a BookmarkContent0
func (t Bookmark_Content) AsBookmarkContent0() (BookmarkContent0, error) {
	var body BookmarkContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBookmarkContent0 overwrites any union data inside the Bookmark_Content as the provided BookmarkContent0
func (t *Bookmark_Content) FromBookmarkContent0(v BookmarkContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBookmarkContent0 performs a merge with any union data inside the Bookmark_Content, using the provided BookmarkContent0
func (t *Bookmark_Content) MergeBookmarkContent0(v BookmarkContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBookmarkContent1 returns the union data inside the Bookmark_Content as a BookmarkContent1
func (t Bookmark_Content) AsBookmarkContent1() (BookmarkContent1, error) {
	var body BookmarkContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBookmarkContent1 overwrites any union data inside the Bookmark_Content as the provided BookmarkContent1
func (t *Bookmark_Content) FromBookmarkContent1(v BookmarkContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBookmarkContent1 performs a merge with any union data inside the Bookmark_Content, using the provided BookmarkContent1
func (t *Bookmark_Content) MergeBookmarkContent1(v BookmarkContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBookmarkContent2 returns the union data inside the Bookmark_Content as a BookmarkContent2
func (t Bookmark_Content) AsBookmarkContent2() (BookmarkContent2, error) {
	var body BookmarkContent2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBookmarkContent2 overwrites any union data inside the Bookmark_Content as the provided BookmarkContent2
func (t *Bookmark_Content) FromBookmarkContent2(v BookmarkContent2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBookmarkContent2 performs a merge with any union data inside the Bookmark_Content, using the provided BookmarkContent2
func (t *Bookmark_Content) MergeBookmarkContent2(v BookmarkContent2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBookmarkContent3 returns the union data inside the Bookmark_Content as a BookmarkContent3
func (t Bookmark_Content) AsBookmarkContent3() (BookmarkContent3, error) {
	var body BookmarkContent3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBookmarkContent3 overwrites any union data inside the Bookmark_Content as the provided BookmarkContent3
func (t *Bookmark_Content) FromBookmarkContent3(v BookmarkContent3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBookmarkContent3 performs a merge with any union data inside the Bookmark_Content, using the provided BookmarkContent3
func (t *Bookmark_Content) MergeBookmarkContent3(v BookmarkContent3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Bookmark_Content) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Bookmark_Content) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
