version: "3"

vars:
  KARAKEEP_VERSION: v0.26.0

tasks:
  default:
    desc: "Build and test the client"
    cmds:
      - task update-dependencies
      - task client:generate
      - task build
      - task test

  clean:
    desc: "Clean build"
    cmds:
      - go clean

  test:
    desc: "Run tests"
    cmds:
      - go test .

  update-dependencies:
    desc: "Update dependencies"
    cmds:
      - go get -u all && go mod tidy

  #############
  ### BUILD ###
  #############

  build:
    desc: "Build the client"
    cmds:
      - CGO_ENABLED=0 go build .

  build:debug:
    desc: "Build the client for debug mode"
    cmds:
      - CGO_ENABLED=0 go build -gcflags=all="-N -l" .

  ##################
  ### API CLIENT ###
  ##################

  client:update:
    desc: "Update git submodule to current version"
    cmds:
      - git submodule update --remote
      - git -C karakeep checkout {{.KARAKEEP_VERSION}}

  client:generate:
    aliases: [gen]
    desc: "Generate API client code"
    cmds:
      - go generate .
