name: Release Go Karakeep

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get current release version
        run: echo "CURRENT_VERSION=$(grep 'KARAKEEP_VERSION:' Taskfile.yml | cut -d ' ' -f4)" >> $GITHUB_ENV

      - name: Get latest release from the repository
        run: echo "LATEST_RELEASE=$(gh release view --json tagName -q '.tagName')" >> $GITHUB_ENV

      - name: Release Go Karakeep
        if: env.CURRENT_VERSION != env.LATEST_RELEASE
        env:
          GH_TOKEN: ${{ github.token }}        
        run: |
          echo "--- Create tag ---"
          git tag "$CURRENT_VERSION"
          git push origin "$CURRENT_VERSION"

          echo "--- Create GitHub release ---"
          gh release create "$CURRENT_VERSION" --generate-notes

          echo "Go Karakeep released successfully!"
